insert into Publisher(Publisher_id, Name) values
(1, 'Penguin Random House'),
(2, 'HarperCollins'),
(3, 'Hachette Book Group'),
(4, 'Simon & Schuster'),
(5, 'Macmillan Publishers'),
(6, 'Scholastic Corporation'),
(7, 'Bloomsbury Publishin'),
(8, 'Γαλάζια Βιβλιοθήκη'),
(9, 'Hamilton House'),
(10, 'Penguin Books'),
(11, 'Vintage Books'),
(12, 'Random House'),
(13, 'Little, Brown and Company'),
(14, 'Faber & Faber'),
(15, 'Allen & Unwin'),
(16, 'Chronicle Books'),
(17, 'Candlewick Press'),
(18, 'Abrams Books'),
(19, 'Houghton Mifflin Harcourt'),
(20, 'W.W. Norton & Company');
